### ISSUE TITLE
LumenTree 600 mit Trucki Stick regelt nicht

### ISSUE THREAD

**Issue by Penny-001** [trucki-eu/Trucki2Shelly-Gateway#16]
Hallo,

ich habe einen LumenTree 600 mit einem Trucki Stick und versuche das nur die Leistung ( Meter) die gerade im Haus verbraucht werden, auch nur eingespeist wird,

leider ohne Erfolg.

Es wird immer die volle Leistung eingespeist.

Was mache ich falsch?

Ich habe nur Solarpanels angeschlossen und keine Batterie.

<img width="396" alt="Bildschirmfoto 2023-07-29 um 14 43 16" src="https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/140943590/98495597-4ec0-4590-b757-9ba2ea899e39">

<img width="396" alt="Bildschirmfoto 2023-07-29 um 14 43 45" src="https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/140943590/6f4b9579-95ff-48a9-ac0d-94a57cb8724b">

 

Gruß

**Comment by trucki-eu** [comment]
Shelly 3EM richtig herum eingebaut?
Target=30W, Average =10 ?

**Comment by Penny-001** [comment]
Ist kein Shelly 3EM, sondern vom IOBROKER ein Datenpunkt.
Es werden mehrere Shelly's addiert und in den Datenpunkt gespeichert.
Der Wert vom dem Datenpunkt wird ja auch in Meter richtig angezeigt.
Target= 30 u. Average =10 ist richtig.

**Comment by trucki-eu** [comment]
Schreibst Dürer MQTT an meterovr und versuchst den ZeroExportController des T2SGs zu verwenden?
Dann ist es wichtig, dass dein Inverter hinter dem Meter hängt und die gemessene Leistung des Meters sich um die Leistung des Inverters reduziert.
Wenn das nicht möglich ist, dann musst Du die die Regelung selber bauen und an ACSetpointOVR die Invterter Leistung schreiben.

**Comment by Penny-001** [comment]
Unter Meter habe ich diesen Link drin:
http://192.168.1.67:8087/get/0_userdata.0.ShellyPlusPlugS.Power_Liste

Json keys: val

nimmt er auch, und zeigt den Wert ja richtig an.

Über MQTT gebe ich nichts ein.

Mit diesem Befehl geht das bei mir:
curl "http://192.168.1.114/?modbus_reg=0&modbus_value= xxx " > NULL

**Comment by trucki-eu** [comment]
Und hängt der Sun auch mit an dem Plug?

**Comment by Penny-001** [comment]
nein.

**Comment by trucki-eu** [comment]
Deshalb geht der Sun auf Maximum. Das Meter will/muss die Leistung des Suns sehen können. Siehe oben.

**Comment by Penny-001** [comment]
Jetzt habe ich es verstanden !

und es läuft!!!!

Vielen Dank für die Hilfe.

Gruß
Björn

**Comment by trucki-eu** [comment]
Prima! Wie hast Du es gelöst? Den Sun mit an den Plug angeschlossen? 
Kann der Plug auch negative Leistungen messen? Sonst könnte es zu Problemen kommen, wenn eine große Last abschaltet!

**Comment by Penny-001** [comment]
ich habe insgesamt 12 Plug's die ich  addiere und in einem Datenpunkt speicher. Der Sun hat einen eigenen Plug der dann davon abgezogen wir.
Es soll auch nur eine Notlösung sein, bis ich ein Shelly 3 EM im Verteilerkasten habe.

Gruß
