### ISSUE TITLE
ZEPC Regelung LT600 - Shelly 3 EM - ZEPC bleibt bei 600 fest stehen - keine Regelung mehr (zu #19)

### ISSUE THREAD

**Issue by Jollinar** [trucki-eu/Trucki2Shelly-Gateway#23]
Hallo Trucki,

jetzt habe ich den Fall wieder und kann dir auch ein paar Screen shots beifügen. 

Battery Voltage = 52,X
Cutoff Voltage im SUN = 44 Volt
Vbat cutoff = 45

also daran sollte es nicht liegen.
Der Shelly sendet korrekte Werte nur der die Regelung scheint nicht zu funktionieren.
ZEPC bleibt auf 600 W und Meter schwankt auf Grund der Verbrauches.

Ich habe dann den Lumentree 600 vom Netz genommen und wieder ans Netz angeschlossen und nun klappt die Regelung wieder scheinbar hängt der sich irgendwo im ZEPC auf und kriegt eine Festwert von 600 W gemeldet und berechnet nicht mehr den aktuellen Wert.

![SUN1](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/141904413/d0e03f7f-08c9-4ba2-b7dc-f2c3d445c8ec)
![SUN2](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/141904413/ba5e5129-1a9b-4040-b3b2-200cae4cde2a)
![SUN3](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/141904413/cf6bac2c-d343-4e8a-9827-4ba6de815ad5)
![shelly1](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/141904413/718730af-1a3b-41ec-beb5-066f3418fe47)

Gruß Carsten

**Comment by Jollinar** [comment]
Hallo Trucki,

der Aufbau ist korrekt beschrieben, Zähler, Shelly und SUN. 

Ein Reboot des TSG-Stick hilft leider nicht, denn nach dem booten setzt der SUN alles sofort wieder auf max. Bisherige Lösung ist SUN vom DC trennen über die Sicherung und dann SUN vom AC trennen. Nach dem Neustart geht alles wieder wie gewohnt.

Cut-off habe ich jetzt auf 40V runtergesetzt aber eben erst nach dem letzten auftreten wobei die Option ja aus gegraut ist weil ich im SUN ja keinen Festwert in W hinterlegt haben.

"Was passiert, wenn Du in diesem Zustand dem SUN manuell eine Leistungsvorgabe über das Drop down Menu unter SUN1 gibst?" <-- kann ich gerade nicht testen da er nicht in dem Zustand ist.

Aktuell läuft die Regelung wieder.

**Comment by Jollinar** [comment]
Moin Trucki,

anbei ein kleines Upate. Heute morgen ist es leider wieder passiert.

Habe dann AC SetPoint manuell gesetzt.

1. AC SetPoint > aktuelle Produktion <-- keine Wirkung 
2. AC SetPoint < aktuelle Produktion <-- Runterregelung auf AC SetPoint
3. AC SetPoint = autommatik <-- kurzfristig versuchte er zu Regeln ging dann aber wieder auf AC SetPoint = 600 

Erste Vermutung war Battery Voltage zu gering da sehr nah am Vbat-Cut off.

Dann kam auch der Cut-Off und das System stellte die Produktion ein, nachdem dann wieder VBat Reboot erreicht wurde, startet die Regelung wieder mit AC SetPoint = 600W also ohne Regelung.

Jetzt gerade hat die Regelung wieder den normal Betrieb begonnen AC SetPoint = ZEPC. 

Wovon hängt ab wann und wie e regelt, gibt es hier vielleicht Abhänigkeiten der Parameter Vbat cutoff, Vbat Reboot, ZEPC ?
Vielleicht wäre es sinnvoll ein Log zu haben das man aktivieren kann um den Verlauf der Parameter zu tracken ?

![Screenshot 2023-08-24 080556](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/141904413/020229ea-95f7-4488-87f9-89d94d9c53c4)

![Screenshot 2023-08-24 080809](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/141904413/bf2f3ee6-473e-451c-8d73-0fe29fe9e5da)

![Screenshot 2023-08-24 080825](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/141904413/f041fb7c-4df4-4021-92b3-9bcea50f73c4)

**Comment by trucki-eu** [comment]
Hallo Carsten,

Viele Dank für die detaillierte Beschreibung. Für mich klingt das stark nach Cutoff im SUN. Der schaltet nämlich nicht hart ab, sondern reduziert erstmal die maximal mögliche Leistung. Den sollte man sowieso ganz abschalten. Zur Sicherheit schaltet das BMS ab, im täglichen Gebrauch das T2SG.
Loggen kann man prima mit MQTT. Da werden jede Menge Werte rausgeschrieben.

Viele Grüße Trucki

**Comment by trucki-eu** [comment]
Komisch. Funktionieren deine Lüfter? Thermal throtteling ist der 2. Grund aus dem der Sun die Leistung reduziert.
Gruß Trucki

**Comment by Jollinar** [comment]
Beide Lüfter laufen einwandfrei. 

Habe sogar die Stecker Ports geprüft ob beider Lüfter korrekt angeschlossen sind. Alles ok.

Heute morgen hatte ich dann wieder eine Aussetzer bei 

Battery Voltage 48,2V 
AC Setpoint = 300W automatisch im Sun gesetzt (Nachzeitmodus)
Regelung = keine

AC Setpoint auf 0 gesetzt und dann wieer ZEPC enabled, alles geht wieder. 

Ab welchem VBatCutoff + X fängt der Sun den an langsam runter zu regeln ?

VbatCutoff 45V
Battery Voltage = 48,2V
Differenz = 3,2V ???

**Comment by trucki-eu** [comment]
Das T2SG kann sowohl Cutoff als auch Nachtmodus. Schalte mal alle automatischen Einstellungen (Cutoff, Timer) im Display des Suns ab.

**Comment by Jollinar** [comment]
Die sind alle komplett aus, die Regelung läuft nur über den T2SG. Dennoch bleibt er manchmal hängen und ich kann dir nicht sagen warum.

**Comment by Jollinar** [comment]
Hi Trucki, ich habe die Config einmal angepasst. und Folgenden Werte eingestellt.

SUN Cut-Off = 44V
SUN Reboot = 48V
Solar Bat = 600W (aktiviert)

TSG Cut-Off = 46V
TSG Reboot = 50V

Zudem habe ich das BMS umgestellt auf
Sec Cut-Off Low= 40V (2,5V)
Sec Cut-Off HIgh = 58,4V (3,65V)

Sowie den Laderegler auf
Max Current / Floating = 54,4 (3,4V pro Zelle)

die letzten Tage hatte ich keine Ausfälle mehr, werde das aber weiter beobachten. Ich gehe ich ggf. davon aus das die Vielzahl der Parameter sich hier ggf. gegenseitig blockiert und ausgehebelt haben.

Gruß Carsten

**Comment by trucki-eu** [comment]
Hallo Carsten,

Vielen Dank für die Rückmeldung. Ich verstehe nicht, warum Du überhaupt einen Cutoff im SUN einstellst?

Viele Grüße Trucki

**Comment by Jollinar** [comment]
Hi Trucki,

hatte ich vorher auch nicht aber da hatte ich dann ja die Probleme ich teste das jetzt mal und dann werden wir sehen.

anderer Frage wäre kann ich im Target bei ZEPC auch negative werte einstellen ?

Gruß Carsten

**Comment by Jollinar** [comment]
Hi Trucki, kann geschlossen werden, der Langzeittest war erfolgreich mit den Einstellungen läuft es ohne Probleme.

Danke für die Hilfe.
