### ISSUE TITLE
MQTT - Home Assistant nur lesene Daten möglich? Aktionen können nicht festgelegt werden.

### ISSUE THREAD

**Issue by marcellofiore** [trucki-eu/Trucki2Shelly-Gateway#28]
Hallo Trucki, leider habe ich festgestellt, dass ich keine Automatisierungen verwenden kann, um z.B. einen Targhet-Wert über MQTT zu setzen.. es wäre großartig, das Ziel auf z.B. -300Watt zu setzen, wenn die Batterie geladen ist, die Sonne scheint und die Paneele produzieren :)

![IMG_9956](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/22861591/22d52bfb-bc0f-4ed8-846f-350feba6f8ed)
![IMG_9957](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/22861591/49b56a8e-7a90-48c3-8dd4-ef404052bc21)

Nur die Sensoren sind zum Ablesen verfügbar. Irgendeine Idee, warum?

![IMG_9959](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/22861591/cfcb8cec-95cf-4318-9890-8aee2161921e)
![IMG_9958](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/22861591/401db032-09cd-49c1-a823-53bff4b6f2ab)

**Comment by erxbout** [comment]
Ich versuche mal zu helfen:

Denke dass im Homeassistant MQTT Autodiscovery kein schreiben mit drin ist..

Bei mir hab ichs gelöst in dem ich einen Helfer angelegt habe:
![2023-09-05-073551_1600x873_scrot](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/68945126/4b0e0b4b-3010-41c4-972e-d76ff5019675)

Mit dem dann eine kleine Automatisierung:
![2023-09-05-073755_1600x900_scrot](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/68945126/d3b18e58-2b59-4a5e-b5a3-c814d23f64d6)

Zum Ändern einfach eine 'Entities' Karte mit dem erstellten Helfer auf dein Dashboard setzen und dort dann den Wert eintragen.

Der wird dann nach 10 sekunden geschrieben (oder wieviel du einstellst, hab ich gemacht falls ich mich doch noch umentscheide)

**Comment by trucki-eu** [comment]
Hallo erxbout,

ja korrekt! Das HADiscovery habe ich auf Wunsch eines Users eingebaut. Leider hat das mit den zu Schreibenden Werten nie richtig funktioniert und der User hat sich nie wieder gemeldet.

Ich schicke Dir gerne den Code wenn Du damit rumspielen möchtest. Schreib mir einfach ne Mail.

Viele Grüße,
Trucki

**Comment by marcellofiore** [comment]
> Ich versuche mal zu helfen:
> 
> Denke dass im Homeassistant MQTT Autodiscovery kein schreiben mit drin ist..
> 
> Bei mir hab ichs gelöst in dem ich einen Helfer angelegt habe: ![2023-09-05-073551_1600x873_scrot](https://user-images.githubusercontent.com/68945126/265596210-4b0e0b4b-3010-41c4-972e-d76ff5019675.png)
> 
> Mit dem dann eine kleine Automatisierung: ![2023-09-05-073755_1600x900_scrot](https://user-images.githubusercontent.com/68945126/265596272-d3b18e58-2b59-4a5e-b5a3-c814d23f64d6.png)
> 
> Zum Ändern einfach eine 'Entities' Karte mit dem erstellten Helfer auf dein Dashboard setzen und dort dann den Wert eintragen.
> 
> Der wird dann nach 10 sekunden geschrieben (oder wieviel du einstellst, hab ich gemacht falls ich mich doch noch umentscheide)

Hallo erxbout, danke für dein Hilfe. Ich versuch es gleich das nach zu bauen, was aber mir noch nicht klar ist, wo soll ich die neue Wert für das Target reinschreiben, bestimmt in payload, ich sehe das aber nicht in dein Code...?

**Comment by erxbout** [comment]
In den Helfer input_number.gridpowertarget

Mit der entities Karte kann man das auf einem dashboard machen

``` yml
type: entities
entities:
  - input_number.gridpowertarget
```

Ansonsten in devices and services -> helpers
Wichtig ist dass der Helper als Number definiert ist, dann ist die Anzeige am Dashboard dem entsprechend

**Comment by erxbout** [comment]
Ich habe den Helfer mit der entities Karte auf meinem dashboard

``` yml
type: entities
entities:
  - input_number.mqttreactorpowertarget
```
Dort ändere ich manuell den Wert, dieser wird dann im payload geschickt

Der payload verträgt templates, deswegen die geschwungenen Klammern, also wird hier der Wert von der Entität geschickt.. das kann natürlich auch ein sensor sein oder jede andere Entität. 
Hier nur ein Beispiel:
``` yml 
payload: "{{ states('sensor.iphone_battery_level') | int }}" 
```

Sollte es ein fixer Wert sein der geschrieben werden soll dann wäre der code wie folgt:

``` yml
service: mqtt.publish
  data:
  qos: "0"
  topic: T2SGFirst/TARGETOVR
  payload: "15"
```

Hope that helps ;)

**Comment by marcellofiore** [comment]
Super, es scheint alles zum Funktioniere, vielen Dank.
