### ISSUE TITLE
cannot get 100% output (600W)

### ISSUE THREAD

**Issue by madejackson** [trucki-eu/Trucki2Shelly-Gateway#46]
When my T2SG is requesting 100% / 600W Output, it does only deliver about 560-570W

Same behaviour with manual MQTT or ZEPC.
I already did a calibration (set CAL to 1).

Is there any way to squeeze out the last 30-40W?

![grafik](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/24832654/fbe6e978-025f-4916-bb97-dc0b2d81b33d)

**Comment by erxbout** [comment]
What is your Voltage supply?

My sun 1000 reports a power limit of 860W because of the supplied 24-27V
On 24V even lower (battery goes empty)

Also is your measuring equipment calibrated correctly?

**Comment by madejackson** [comment]
The values all come from T2SG directly (via mqtt)
The solar input is higher than 600W at the same time, so that's why i wanna also output the max 600W. Rest goes into the battery, which is 26V right now.

![grafik](https://github.com/trucki-eu/Trucki2Shelly-Gateway/assets/24832654/3affa1d4-c9ca-4138-a164-14917470f387)

**Comment by trucki-eu** [comment]
Hast Du einen SUN600 oder 1000? Model 2023 oder 2024? Trucki RS485 Platine oder T2SUN Stick?

**Comment by madejackson** [comment]
Es ist ein SUN600 2023 mit T2SG

**Comment by trucki-eu** [comment]
Ja, dann ist das so. Ich wüsste nicht, was man da noch einstellen könnte. Gruß,
Trucki
